require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

async function fix() {
  try {
    const res = await pool.query(`
      SELECT column_name, column_default, data_type 
      FROM information_schema.columns 
      WHERE table_name = 'expenses';
    `);
    console.log("Table columns:");
    console.table(res.rows);

    // If id has no default, try to fix it
    const idCol = res.rows.find(r => r.column_name === 'id');
    if (!idCol.column_default) {
       console.log("Fixing id column to auto-increment...");
       // check if it is INT or UUID
       if (idCol.data_type === 'integer' || idCol.data_type === 'bigint') {
           await pool.query('ALTER TABLE expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;');
           console.log("Added Identity generation to expenses.id");
       } else if (idCol.data_type === 'uuid') {
           await pool.query('ALTER TABLE expenses ALTER COLUMN id SET DEFAULT gen_random_uuid();');
           console.log("Added gen_random_uuid() to expenses.id");
       }
    } else {
       console.log("id already has default:", idCol.column_default);
    }
  } catch (err) {
    console.error(err);
  } finally {
    pool.end();
  }
}

fix();
